### ISSUE TITLE
Timecard System TODO list to get to V1.0

### ISSUE THREAD

**Issue by ChromesDuzez** [ChromesDuzez/Twitch-TikTok-Discord-Queue-Bot#1]
- [x] Create a method to refresh all views attached to messages on bot startup OR ELSE THEY WONT WORK
- [x] Have the `createclock` definition query to initialize the embed w/ thecorrect clocked in status (in/out)... (currently creates a clock that shows not clocked in and could become dy-synced with the database and cause issues and big bugs). VERY IMPORTANT
- [x] Admin approval message/button for chift clock-in's via automated or forced mobile clock-in's into `TIMECARD_ADMIN_CHANNEL_ID`. Store that message info in `punch_clock` table under `checkChannelId` and `checkMessageId`.
- [x] create additions to the clock view to support work time punches... add two buttons to the view `Pool` & `Service` both which bring up a form to submit the `customer` name and swap to the view the respective `pool` or `service` view w/ its button to end the "timer" for the work or the button to edit the `customer` name and the button to stop the time but put in a custome time in case they forgot to stop timer or wish to put it in after the fact. (This will stop the user from being able to clock out before the ending of his/her work for a customer. 
- [x] Clarify the `ignore lunch break` button
- [x] Fix that admins were not able to clock in and out other users
- [x] Need to support all of the types of employees 
     - Temp employees which have weekly reports through the temp agency
     - Company employees that are salaried (biweekly)
     - Company employees that are paid hourly (biweekly)
- [ ] Create a way to manually add `service` or `pool` work to a timecard after the shift has concluded (might have made a solution in the last point by having a button on the `worktime` view that allows the employee to end the work and put in a custom time).
- [x] More unique timecard report file names by adding the employee group to the name
- [ ] Setup a second default employee group that is for all active employees and/or all employees
- [ ] Log all events/changes in `TIMECARD_LOG_ID` channel
- [ ] Setup an event to generate the timecard reports for the week and send it into the `TIMECARD_REPORTS_CHANNEL_ID` 
- [ ] Add support for "Bonus Time" (aka Bonuses, Holiday, Vacation, Sick Days)
- [ ] Add support for employee Main work type, Shop, Office, Service, Construction. Where the Lunch gets deducted from.
- [ ] Fix approval button for editing an employee's punch
- [ ] Punch In/Out Kiosk Support
- [ ] Grouping of employees support so that two guys who are working together all day don't have to each punch in and out of jobsites, but only one of them needs to.
- [ ] Construction Job Report
- [ ] Hipp Invoice Report

**Comment by ChromesDuzez** [comment]
Minor Changes I want/need to make.
- [ ] Add a way to manage the groups and their members from within discord.
- [ ] Add the ability for /viewtimecard to be able to run with no parameter (defaulting) to user's time. atm no non-admin user can run the command, if there is no parameter given they should be able to run it and it responds with the ephemeral message
- [ ] In the view timecard response if the punch out date does not match the punch in date it should specify which date the punch out happened at. Also it should append the calculated duration so no mental math has to happen. (Potentially also listing the time in 12hr format. Or better yet depending on the user's preference display 12hr or 24hr.)
